"""Reactivity predicate algebra property tests (W6.A1).

Invariants
----------
The predicate algebra is the boolean lattice generated by
``EntryKind / HasTopic / HasDomain / HasOwner / SpeakerNotOwner`` under
``& | ~``. For any predicates p, q, r and any ledger entry e, the
following identities MUST hold:

    A. associativity:    p & (q & r) ≡ (p & q) & r
    B. associativity:    p | (q | r) ≡ (p | q) | r
    C. commutativity:    p & q ≡ q & p
    D. commutativity:    p | q ≡ q | p
    E. involution:       ~~p ≡ p
    F. distributive:     (p & q) | (p & r) ≡ p & (q | r)
    G. distributive:     (p | q) & (p | r) ≡ p | (q & r)
    H. de Morgan:        ~(p & q) ≡ ~p | ~q
    I. de Morgan:        ~(p | q) ≡ ~p & ~q
    J. identity (TRUE):  p & TRUE ≡ p
    K. identity (FALSE): p | FALSE ≡ p
    L. annihilator:      p & FALSE ≡ FALSE   ;   p | TRUE ≡ TRUE
    M. idempotence:      p & p ≡ p           ;   p | p ≡ p

These are the laws of any boolean algebra. Hypothesis fuzzes a) the
choice of primitive predicates and b) the entry shape; for each (e,
predicates) pair we evaluate both sides and assert equality.

Why this matters
----------------
The composition operators are implemented in ``predicates._PredicateBase``
as straight ``And`` / ``Or`` / ``Not`` factories — there's no algebraic
simplifier. The laws are what make ``EntryKind("chat_received") & HasTopic()``
equivalent to ``HasTopic() & EntryKind("chat_received")`` regardless of
short-circuit timing. Reactivity authors rely on this every day.
"""

from __future__ import annotations

import asyncio
from datetime import UTC, datetime
from typing import Any
from uuid import UUID, uuid4

from hypothesis import HealthCheck, given, settings, strategies as st

from wormbase_reactivities.predicates import (
    EntryKind,
    HasDomain,
    HasOwner,
    HasTopic,
    Not,
    SpeakerNotOwner,
    _PredicateBase,
)
from wormbase_reactivities.protocol import ReactivityContext


# ---------------------------------------------------------------------------
# Synthetic TRUE / FALSE primitives for the identity / annihilator laws.
# ---------------------------------------------------------------------------


class _True(_PredicateBase):
    async def match(self, entry: dict[str, Any], context: ReactivityContext) -> bool:
        return True


class _False(_PredicateBase):
    async def match(self, entry: dict[str, Any], context: ReactivityContext) -> bool:
        return False


# Register primitives the strategy can pick from.
def _primitives() -> st.SearchStrategy[_PredicateBase]:
    return st.one_of(
        st.just(EntryKind("chat_received")),
        st.just(EntryKind("memory_written")),
        st.just(EntryKind("execute")),
        st.builds(EntryKind, st.text(min_size=1, max_size=8)),
        st.just(HasTopic()),
        st.just(HasDomain()),
        st.just(HasOwner()),
        st.just(SpeakerNotOwner()),
        st.just(_True()),
        st.just(_False()),
    )


# ---------------------------------------------------------------------------
# Entry strategy — covers chat_received / execute / propose envelopes,
# with various args.
# ---------------------------------------------------------------------------


def _entry_strategy() -> st.SearchStrategy[dict[str, Any]]:
    person_a = uuid4()
    person_b = uuid4()
    return st.fixed_dictionaries(
        {
            "kind": st.sampled_from(
                ["execute", "chat_received", "memory_written", "propose", "resolve"]
            ),
            "ts": st.just(datetime(2026, 4, 22, 12, 0, tzinfo=UTC)),
            "seq": st.integers(min_value=1, max_value=1000),
            "payload": st.fixed_dictionaries(
                {
                    "tool": st.sampled_from(
                        [
                            "emit_chat_received",
                            "channel_adapter.emit_chat_received",
                            "emit_memory_written",
                            "emit_unknown",
                            "",
                        ]
                    ),
                    "args": st.fixed_dictionaries(
                        {
                            "topic": st.one_of(st.none(), st.text(max_size=8)),
                            "domain": st.one_of(st.none(), st.text(max_size=8)),
                            "owner_id": st.one_of(st.none(), st.sampled_from([str(person_a), str(person_b)])),
                            "sender_person": st.one_of(st.none(), st.sampled_from([str(person_a), str(person_b)])),
                        }
                    ),
                }
            ),
        }
    )


def _ctx() -> ReactivityContext:
    return ReactivityContext(
        ledger=None,
        company_id=UUID("00000000-0000-0000-0000-000000000099"),
        registry=None,
        now=lambda: datetime(2026, 4, 22, tzinfo=UTC),
    )


def _eval(pred: _PredicateBase, entry: dict[str, Any]) -> bool:
    return asyncio.run(pred.match(entry, _ctx()))


# ---------------------------------------------------------------------------
# Property tests
# ---------------------------------------------------------------------------


_HSETTINGS = settings(
    max_examples=200,
    deadline=None,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.data_too_large],
)


@given(p=_primitives(), q=_primitives(), r=_primitives(), entry=_entry_strategy())
@_HSETTINGS
def test_and_associativity(
    p: _PredicateBase, q: _PredicateBase, r: _PredicateBase, entry: dict[str, Any]
) -> None:
    """Invariant A: AND is associative — p & (q & r) ≡ (p & q) & r.

    For all primitive predicates p, q, r and all entries e:
        eval(p & (q & r), e) == eval((p & q) & r, e)
    """
    lhs = _eval(p & (q & r), entry)
    rhs = _eval((p & q) & r, entry)
    assert lhs == rhs


@given(p=_primitives(), q=_primitives(), r=_primitives(), entry=_entry_strategy())
@_HSETTINGS
def test_or_associativity(
    p: _PredicateBase, q: _PredicateBase, r: _PredicateBase, entry: dict[str, Any]
) -> None:
    """Invariant B: OR is associative — p | (q | r) ≡ (p | q) | r."""
    assert _eval(p | (q | r), entry) == _eval((p | q) | r, entry)


@given(p=_primitives(), q=_primitives(), entry=_entry_strategy())
@_HSETTINGS
def test_and_commutativity(
    p: _PredicateBase, q: _PredicateBase, entry: dict[str, Any]
) -> None:
    """Invariant C: AND is commutative — p & q ≡ q & p."""
    assert _eval(p & q, entry) == _eval(q & p, entry)


@given(p=_primitives(), q=_primitives(), entry=_entry_strategy())
@_HSETTINGS
def test_or_commutativity(
    p: _PredicateBase, q: _PredicateBase, entry: dict[str, Any]
) -> None:
    """Invariant D: OR is commutative — p | q ≡ q | p."""
    assert _eval(p | q, entry) == _eval(q | p, entry)


@given(p=_primitives(), entry=_entry_strategy())
@_HSETTINGS
def test_double_negation_is_involutive(
    p: _PredicateBase, entry: dict[str, Any]
) -> None:
    """Invariant E: ~~p ≡ p (involution).

    Two negations cancel; the predicate value is unchanged.
    """
    assert _eval(Not(Not(p)), entry) == _eval(p, entry)


@given(p=_primitives(), q=_primitives(), r=_primitives(), entry=_entry_strategy())
@_HSETTINGS
def test_and_distributes_over_or(
    p: _PredicateBase, q: _PredicateBase, r: _PredicateBase, entry: dict[str, Any]
) -> None:
    """Invariant F: AND distributes over OR — p & (q | r) ≡ (p & q) | (p & r)."""
    lhs = _eval(p & (q | r), entry)
    rhs = _eval((p & q) | (p & r), entry)
    assert lhs == rhs


@given(p=_primitives(), q=_primitives(), r=_primitives(), entry=_entry_strategy())
@_HSETTINGS
def test_or_distributes_over_and(
    p: _PredicateBase, q: _PredicateBase, r: _PredicateBase, entry: dict[str, Any]
) -> None:
    """Invariant G: OR distributes over AND — p | (q & r) ≡ (p | q) & (p | r)."""
    lhs = _eval(p | (q & r), entry)
    rhs = _eval((p | q) & (p | r), entry)
    assert lhs == rhs


@given(p=_primitives(), q=_primitives(), entry=_entry_strategy())
@_HSETTINGS
def test_de_morgan_and(
    p: _PredicateBase, q: _PredicateBase, entry: dict[str, Any]
) -> None:
    """Invariant H: de Morgan — ~(p & q) ≡ ~p | ~q."""
    assert _eval(Not(p & q), entry) == _eval(Not(p) | Not(q), entry)


@given(p=_primitives(), q=_primitives(), entry=_entry_strategy())
@_HSETTINGS
def test_de_morgan_or(
    p: _PredicateBase, q: _PredicateBase, entry: dict[str, Any]
) -> None:
    """Invariant I: de Morgan — ~(p | q) ≡ ~p & ~q."""
    assert _eval(Not(p | q), entry) == _eval(Not(p) & Not(q), entry)


@given(p=_primitives(), entry=_entry_strategy())
@_HSETTINGS
def test_and_identity_with_true(
    p: _PredicateBase, entry: dict[str, Any]
) -> None:
    """Invariant J: p & TRUE ≡ p."""
    assert _eval(p & _True(), entry) == _eval(p, entry)


@given(p=_primitives(), entry=_entry_strategy())
@_HSETTINGS
def test_or_identity_with_false(
    p: _PredicateBase, entry: dict[str, Any]
) -> None:
    """Invariant K: p | FALSE ≡ p."""
    assert _eval(p | _False(), entry) == _eval(p, entry)


@given(p=_primitives(), entry=_entry_strategy())
@_HSETTINGS
def test_and_with_false_is_false(
    p: _PredicateBase, entry: dict[str, Any]
) -> None:
    """Invariant L (AND annihilator): p & FALSE ≡ FALSE."""
    assert _eval(p & _False(), entry) is False


@given(p=_primitives(), entry=_entry_strategy())
@_HSETTINGS
def test_or_with_true_is_true(
    p: _PredicateBase, entry: dict[str, Any]
) -> None:
    """Invariant L (OR annihilator): p | TRUE ≡ TRUE."""
    assert _eval(p | _True(), entry) is True


@given(p=_primitives(), entry=_entry_strategy())
@_HSETTINGS
def test_and_idempotence(
    p: _PredicateBase, entry: dict[str, Any]
) -> None:
    """Invariant M: p & p ≡ p (idempotence)."""
    assert _eval(p & p, entry) == _eval(p, entry)


@given(p=_primitives(), entry=_entry_strategy())
@_HSETTINGS
def test_or_idempotence(
    p: _PredicateBase, entry: dict[str, Any]
) -> None:
    """Invariant M: p | p ≡ p (idempotence)."""
    assert _eval(p | p, entry) == _eval(p, entry)
