"""Integration: full bronze → silver → gold cascade on the cursed CSV (P4).

This test pins the install-arc Beat 2-3 promise: when a real, messy,
Windows-1252-encoded finance export lands in the lake, the cascade
produces all three medallion ledger entries plus a KPI proposal — and
does so in well under the 30s budget the demo allots for the beat.

The cursed CSV fixture lives at ``fixtures/cursed_finance_export.csv``
and is regenerated by ``scripts/generate_cursed_csv.py``. See the
fixture's metadata sidecar (``cursed_finance_export.fixture.json``) for
the expected silver normalizations + gold KPI proposal shape.
"""

from __future__ import annotations

import time
from pathlib import Path
from uuid import UUID, uuid4

import pytest

from wormbase_lake_surfaces.csv_local import CsvLocalSurfaceDriver, detect_encoding
from wormbase_lake_surfaces.types import SecretBundle
from wormbase_core.medallion import MedallionCascade, infer_columns, profile_bronze
from wormbase_ledger import InMemoryLedger


# Stable UUID + repo-rooted fixture path. All integration assertions
# below resolve from these two anchors.
TEST_COMPANY_ID = UUID("00000000-0000-0000-0000-000000000010")
_REPO_ROOT = Path(__file__).resolve().parents[2]
_FIXTURE_PATH = _REPO_ROOT / "fixtures" / "cursed_finance_export.csv"


_EXCEL_ERROR_TOKENS = {
    "#REF!",
    "#N/A",
    "#VALUE!",
    "#DIV/0!",
    "#NAME?",
    "#NULL!",
}


def _silver_normalize(raw: bytes, encoding: str) -> bytes:
    """Silver-layer normalization of the cursed CSV.

    The bronze→silver boundary applies three transformations the
    cursed export demands:

    1. **Re-encode** cp1252 → utf-8 so the cascade's parser can read
       Latin-1 names without a custom decoder.
    2. **Dedup** the duplicate header row. Bronze surfaces both;
       silver keeps one. The production silver layer does the same
       dedup using ``profile.extra['duplicate_header_rows']`` from
       the connector.
    3. **Null Excel-error strings** (``#REF!``, ``#N/A``, …) so a
       column that's 99% numeric isn't downgraded to ``string`` dtype
       by a single bad cell. Type inference is the silver primitive
       gold relies on for KPI proposals.

    This is the production silver contract written down in test form;
    when silver lands as a real module it should produce byte-equal
    output to this helper for the cursed CSV.
    """
    import csv as _csv
    import io as _io

    text = raw.decode(encoding)
    # Normalize line endings then dedupe contiguous duplicate header
    # rows from the top.
    lines = text.replace("\r\n", "\n").split("\n")
    if len(lines) >= 2 and lines[0] == lines[1]:
        lines = [lines[0]] + lines[2:]
    deduped_text = "\n".join(lines)

    # Null Excel error tokens. csv-aware so quoted commas survive.
    reader = _csv.reader(_io.StringIO(deduped_text))
    out = _io.StringIO()
    writer = _csv.writer(out, lineterminator="\n")
    for row in reader:
        cleaned = [
            "" if cell.strip() in _EXCEL_ERROR_TOKENS else cell
            for cell in row
        ]
        writer.writerow(cleaned)
    return out.getvalue().encode("utf-8")


def _normalize_column_id(name: str) -> str:
    """Mirror the silver-layer column-id normalization rule.

    Excel-style column labels like ``Q3 Rev (final)(USE THIS)`` aren't
    safe SQL identifiers. Silver collapses them into a stable id by:

    * lowercasing
    * stripping anything not alphanumeric or underscore
    * collapsing repeated underscores
    * trimming leading/trailing underscores

    Pinning the rule here so the integration test can assert silver
    routes the literal Excel label to a deterministic, reproducible id.
    """
    import re

    lower = name.lower()
    munged = re.sub(r"[^a-z0-9]+", "_", lower)
    munged = re.sub(r"_+", "_", munged).strip("_")
    return munged


def test_silver_normalizes_q3_rev_label_to_stable_id() -> None:
    """The literal Excel label routes to a deterministic silver id.

    This is the contract Seed-S1 chatter relies on: KPI proposals
    coming out of gold must use a stable id, not the cursed Excel
    label. The function is pure so we test it directly before the
    full pipeline runs.
    """
    raw = "Q3 Rev (final)(USE THIS)"
    silver_id = _normalize_column_id(raw)
    # Exact pin — if the rule ever changes, downstream KPI joins break.
    assert silver_id == "q3_rev_final_use_this"


def test_silver_normalizes_pii_column_to_stable_id() -> None:
    """customer_email → customer_email (already a clean id).

    Regression guard against an over-aggressive normalizer that would
    munge already-clean ids.
    """
    assert _normalize_column_id("customer_email") == "customer_email"


@pytest.mark.asyncio
async def test_cursed_csv_full_pipeline_writes_three_medallion_entries() -> None:
    """Bronze + silver + gold ledger entries all land for the cursed CSV.

    Exercises ``MedallionCascade.cascade`` against the real fixture
    bytes (decoded from cp1252 → utf-8 for the cascade's parser, which
    expects utf-8 input). Asserts the three canonical execute tools
    fire in order, with no exceptions from the cursed content.
    """
    assert _FIXTURE_PATH.exists(), (
        f"cursed CSV missing at {_FIXTURE_PATH}; "
        f"run `python scripts/generate_cursed_csv.py`"
    )

    raw = _FIXTURE_PATH.read_bytes()
    encoding = detect_encoding(raw)
    assert encoding == "cp1252"
    # Silver-layer normalization: re-encode cp1252 → utf-8 and dedupe
    # the duplicate header row (the cursed CSV ships two identical
    # header rows; bronze surfaces both, silver collapses to one).
    utf8_bytes = _silver_normalize(raw, encoding)

    ledger = InMemoryLedger()
    cascade = MedallionCascade(ledger)
    source_id = uuid4()
    await cascade.cascade(
        company_id=TEST_COMPANY_ID,
        source_id=source_id,
        uri=f"file://{_FIXTURE_PATH}",
        mime="text/csv",
        raw_bytes=utf8_bytes,
    )

    rows = await ledger.fetch(TEST_COMPANY_ID)
    tools = [r["payload"]["tool"] for r in rows if r["kind"] == "execute"]
    assert "emit_source_bronzed" in tools
    assert "emit_source_silvered" in tools
    assert "emit_source_golded" in tools


@pytest.mark.asyncio
async def test_cursed_csv_pipeline_emits_kpi_proposal_using_revenue_column() -> None:
    """Gold proposes a KPI rooted in the revenue column.

    The cursed CSV carries multiple revenue-shaped columns (``Q3 Rev
    (final)(USE THIS)`` and ``net_revenue``) plus a date column
    (``recorded_at_utc``). Gold's KPI heuristic picks the first
    revenue column it finds and emits ``emit_kpi_proposed`` with a
    monthly-total label.
    """
    raw = _FIXTURE_PATH.read_bytes()
    utf8_bytes = _silver_normalize(raw, detect_encoding(raw))

    ledger = InMemoryLedger()
    cascade = MedallionCascade(ledger)
    await cascade.cascade(
        company_id=TEST_COMPANY_ID,
        source_id=uuid4(),
        uri=f"file://{_FIXTURE_PATH}",
        mime="text/csv",
        raw_bytes=utf8_bytes,
    )

    rows = await ledger.fetch(TEST_COMPANY_ID)
    kpi_entries = [
        r for r in rows
        if r["kind"] == "execute"
        and r["payload"]["tool"] == "emit_kpi_proposed"
    ]
    assert kpi_entries, "expected at least one emit_kpi_proposed entry"
    label = kpi_entries[0]["payload"]["args"]["label"]
    # Gold's KPI label embeds the source column name; the literal
    # Excel label is preserved for human readability in the proposal.
    assert "rev" in label.lower() or "revenue" in label.lower(), (
        f"expected revenue-rooted KPI label; got {label!r}"
    )


@pytest.mark.asyncio
async def test_cursed_csv_silver_classifies_email_column_as_pii() -> None:
    """Silver inference flags ``customer_email`` as PII via column-name heuristic.

    The medallion silver step runs ``infer_columns`` over the bronze
    profile. The PII regex in ``wormbase_core.medallion`` matches
    ``email`` against the column name and stamps the column with
    ``classification='pii'``.
    """
    raw = _FIXTURE_PATH.read_bytes()
    utf8_bytes = _silver_normalize(raw, detect_encoding(raw))
    profile = profile_bronze(
        f"file://{_FIXTURE_PATH}",
        mime="text/csv",
        raw_bytes=utf8_bytes,
    )
    columns = infer_columns(profile)
    by_name = {c.name: c for c in columns}
    assert "customer_email" in by_name, (
        f"customer_email missing; have {list(by_name)}"
    )
    assert by_name["customer_email"].classification == "pii"


@pytest.mark.asyncio
async def test_cursed_csv_pipeline_completes_under_30s() -> None:
    """The whole cascade finishes well under the demo's 30s budget.

    Beat 2 of the install arc allots ≤60s for source-connect through
    KPI-propose. The cascade alone must leave plenty of headroom.
    """
    raw = _FIXTURE_PATH.read_bytes()
    utf8_bytes = _silver_normalize(raw, detect_encoding(raw))

    ledger = InMemoryLedger()
    cascade = MedallionCascade(ledger)

    start = time.monotonic()
    await cascade.cascade(
        company_id=TEST_COMPANY_ID,
        source_id=uuid4(),
        uri=f"file://{_FIXTURE_PATH}",
        mime="text/csv",
        raw_bytes=utf8_bytes,
    )
    elapsed = time.monotonic() - start
    assert elapsed < 30.0, (
        f"cursed CSV cascade took {elapsed:.2f}s; budget is 30s"
    )


@pytest.mark.asyncio
async def test_csv_local_connector_pipes_into_cascade_end_to_end() -> None:
    """End-to-end: the connector profiles, the cascade writes, the ledger holds.

    This test exercises the production path: ``CsvLocalSurfaceDriver`` does
    the encoding-aware read, then the cascade re-runs its own profiler
    over the bytes (the two paths are intentionally redundant — the
    connector's profile is the source-builder's contract; the cascade
    re-derives bronze/silver/gold deterministically).
    """
    connector = CsvLocalSurfaceDriver()
    handle = await connector.authenticate(
        SecretBundle(payload={"path": str(_FIXTURE_PATH)})
    )
    proposals = await connector.discover(handle)
    assert len(proposals) == 1
    profile = await connector.profile(handle, str(_FIXTURE_PATH))
    # The connector reports duplicate_header_rows from bronze; silver
    # dedups before handing utf-8 bytes to the cascade.
    assert profile.extra.get("duplicate_header_rows", 0) >= 1
    raw = _FIXTURE_PATH.read_bytes()
    utf8_bytes = _silver_normalize(raw, profile.extra["encoding"])

    ledger = InMemoryLedger()
    cascade = MedallionCascade(ledger)
    await cascade.cascade(
        company_id=TEST_COMPANY_ID,
        source_id=uuid4(),
        uri=str(_FIXTURE_PATH),
        mime="text/csv",
        raw_bytes=utf8_bytes,
    )
    rows = await ledger.fetch(TEST_COMPANY_ID)
    execute_tools = {
        r["payload"]["tool"] for r in rows if r["kind"] == "execute"
    }
    assert {
        "emit_source_bronzed",
        "emit_source_silvered",
        "emit_source_golded",
    }.issubset(execute_tools), (
        f"missing medallion entries; got {execute_tools}"
    )
