#!/bin/sh
# WormBase Hermes spike entrypoint.
#
# Renders a minimal ~/.hermes/cli-config.yaml + ~/.hermes/.env from
# container env, installs the wire-tap hook into ~/.hermes/hooks/, and
# execs `hermes gateway run`.
#
# Per docs/superpowers/specs/2026-04-27-openclaw-to-hermes-migration.md §7
# Q7: dumb gateway. LLM routing is disabled — worm-core handles all LLM
# calls. We point Hermes's model at a local stub URL so its model
# selection logic doesn't fight us; it's never actually called because
# we don't enable any agent skill that would request inference.
#
# The wire-tap hook lives at /opt/hermes/spike-hook/ in the image (bind-
# mounted from infra/hermes/hooks/wire-tap/ in docker-compose for fast
# iteration) and is symlinked into ~/.hermes/hooks/wire-tap/ at boot.

set -e

log() { echo "[wormbase-hermes-entrypoint] $*" >&2; }

HERMES_DATA="${HERMES_HOME:-/opt/data}"
HOOKS_DIR="${HERMES_DATA}/hooks"
CONFIG_PATH="${HERMES_DATA}/cli-config.yaml"
ENV_PATH="${HERMES_DATA}/.env"

mkdir -p "$HOOKS_DIR" "${HERMES_DATA}/logs"

# --- Hook install ---------------------------------------------------------
# Bind-mount source for the wire-tap hook. We copy rather than symlink
# because Hermes's HookRegistry walks the directory and stat()s files;
# bind-mount is fine, but copying makes the hook self-contained inside
# the volume so a crash-loop doesn't lose the hook content.
SRC_HOOK_DIR=/opt/hermes/spike-hook
if [ -d "$SRC_HOOK_DIR" ]; then
  log "installing wire-tap hook from ${SRC_HOOK_DIR} -> ${HOOKS_DIR}/wire-tap"
  rm -rf "${HOOKS_DIR}/wire-tap"
  mkdir -p "${HOOKS_DIR}/wire-tap"
  cp "${SRC_HOOK_DIR}/HOOK.yaml" "${HOOKS_DIR}/wire-tap/HOOK.yaml"
  cp "${SRC_HOOK_DIR}/handler.py" "${HOOKS_DIR}/wire-tap/handler.py"
else
  log "warning: ${SRC_HOOK_DIR} not present — wire-tap hook will not fire"
fi

# --- .env render ----------------------------------------------------------
# Hermes reads ~/.hermes/.env at boot. We pass through the Slack tokens
# and the spike endpoint URL the hook posts to.
log "rendering ${ENV_PATH}"
cat > "$ENV_PATH" <<EOF
# Generated by wormbase-hermes-entrypoint.sh — do not edit by hand.
SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN_BASEWORM:-}
SLACK_APP_TOKEN=${SLACK_APP_TOKEN_BASEWORM:-}
WORMBASE_HERMES_SPIKE_ENDPOINT=${WORMBASE_HERMES_SPIKE_ENDPOINT:-http://channel-adapter-hermes-spike:18790/hermes-spike}
WORMBASE_HERMES_TENANT=${WORMBASE_TENANT_ID:-baseworm}
# H1 spike finding (2026-04-27): Hermes auth-gates the agent loop —
# agent:start fires AFTER the user-allowlist check, so any inbound from
# a non-allowlisted user gets dropped before the wire-tap can see it.
# WormBase doesn't use Hermes for auth (we use ledger role grants), so
# we open the gateway to all users at the platform layer; ledger-level
# governance still applies downstream.
GATEWAY_ALLOW_ALL_USERS=${GATEWAY_ALLOW_ALL_USERS:-true}
EOF

# --- cli-config.yaml render ----------------------------------------------
# Minimal config: Slack platform only, dummy provider so Hermes doesn't
# fail to start if it touches model config, no skills, no memory.
#
# The `model.provider: custom` + bogus base_url means any inference call
# fails immediately — that's intentional. We don't WANT Hermes inferring;
# we want it as a dumb gateway that fires `agent:start` and lets the
# wire-tap hook capture the inbound envelope.
log "rendering ${CONFIG_PATH}"
cat > "$CONFIG_PATH" <<'EOF'
# Generated by wormbase-hermes-entrypoint.sh — do not edit by hand.
# Spike config: dumb gateway. No LLM calls, no memory, no skills.

model:
  default: "stub/none"
  provider: "custom"
  base_url: "http://127.0.0.1:9/v1"

# Single-platform: Slack. Other adapters disabled.
platforms:
  enabled:
    slack: [hermes-slack]

# Disable everything that would write state outside the ledger.
memory:
  enabled: false

skills:
  enabled: false
EOF

log "starting hermes gateway"
log "  config: ${CONFIG_PATH}"
log "  hooks:  $(ls "$HOOKS_DIR" 2>/dev/null | tr '\n' ' ')"

# Hermes resolves $HERMES_HOME for ~/.hermes; we already exported it.
# The `gateway run` command boots the long-running process.
exec hermes gateway run
