/**
 * POST /api/ask — dashboard's "Ask the worm" affordance.
 *
 * Removes the "I have to set up Slack to evaluate" friction. The route
 * forwards the question to worm-core's ``POST /api/v1/worm/ask``
 * endpoint when the ``WORMBASE_LEDGER_API_TOKEN`` env var is set —
 * upstream synthesises a ``chat_received`` PEVR cycle, fires the
 * production ``MentionResponseReactivity``, and returns the captured
 * worm reply text. Same code path as production chat.
 *
 * When the token is absent (e.g. local dev without the worm-core
 * service), the route returns the honest "wiring note" stub — never
 * inventing an answer. The body shape is identical so the panel
 * renders the same regardless of upstream availability.
 */
import { NextResponse } from "next/server";

import { getTenantFromCookies } from "../../../lib/tenant-cookies";
import { askWorm } from "../../../lib/server/worm-core-write";

export const dynamic = "force-dynamic";
export const revalidate = 0;

interface AskRequestBody {
  question?: unknown;
}

export interface AskResponseBody {
  ok: boolean;
  answer: string;
  references: Array<{ kind: string; ref: string }>;
  /** When true, the answer was generated by the worm-core /api/v1/worm/ask
   *  pass-through. When false, the dashboard returned the honest stub. */
  passthrough: boolean;
  /** Optional trace metadata: the synthetic in-app channel and the chat
   *  reply id. The Ask panel uses these to deep-link into /trace. */
  channel_id?: string;
  chat_reply_id?: string | null;
  chat_received_seq?: number | null;
}

const STUB_MESSAGE =
  "The Ask The Worm endpoint is wired to the dashboard but worm-core is " +
  "not reachable from this server. Set WORMBASE_LEDGER_API_TOKEN and " +
  "WORMBASE_LEDGER_API_BASE so this route can pass-through to " +
  "/api/v1/worm/ask. Until then, post your question in your worm channel " +
  "and the conversational loop will answer with full ledger evidence.";

function isPassthroughEnabled(): boolean {
  return Boolean((process.env.WORMBASE_LEDGER_API_TOKEN ?? "").trim());
}

export async function POST(req: Request) {
  let body: AskRequestBody = {};
  try {
    body = (await req.json()) as AskRequestBody;
  } catch {
    return NextResponse.json(
      {
        ok: false,
        answer: "The request body must be JSON with a `question` field.",
        references: [],
        passthrough: false,
      } satisfies AskResponseBody,
      { status: 400 },
    );
  }

  const question = typeof body.question === "string" ? body.question.trim() : "";
  if (!question) {
    return NextResponse.json(
      {
        ok: false,
        answer: "Please type a question first.",
        references: [],
        passthrough: false,
      } satisfies AskResponseBody,
      { status: 400 },
    );
  }

  if (!isPassthroughEnabled()) {
    // Honest stub — never invent an answer.
    return NextResponse.json(
      {
        ok: true,
        answer: STUB_MESSAGE,
        references: [],
        passthrough: false,
      } satisfies AskResponseBody,
    );
  }

  // Pass-through to worm-core. Tenant is read from the request cookies
  // so per-tenant isolation matches every other dashboard write.
  const tenant = await getTenantFromCookies();
  try {
    const upstream = await askWorm({
      tenantSlug: tenant.slug,
      question,
    });
    return NextResponse.json(
      {
        ok: upstream.ok,
        answer: upstream.answer,
        references: upstream.references ?? [],
        passthrough: true,
        channel_id: upstream.channel_id,
        chat_reply_id: upstream.chat_reply_id ?? null,
        chat_received_seq: upstream.chat_received_seq ?? null,
      } satisfies AskResponseBody,
    );
  } catch (err) {
    return NextResponse.json(
      {
        ok: false,
        answer:
          "The worm-core /api/v1/worm/ask passthrough failed: " +
          ((err as Error).message ?? "unknown error"),
        references: [],
        passthrough: false,
      } satisfies AskResponseBody,
      { status: 502 },
    );
  }
}
