/** @type {import('next').NextConfig} */

// W7.A4 — when the dashboard is exposed through a cloudflared tunnel for
// remote demos, Claude Desktop can't reach worm-core's MCP port (9911)
// directly on the host. Instead, the snippet generated by
// ConnectClaudeDesktopPanel points at ``<tunnel>/mcp`` and Next.js
// transparently proxies that traffic to the worm-core MCP server over
// the compose network. See apps/dashboard/lib/server/dashboard-url.ts
// for the matching URL helper.
//
// We can't blindly rewrite ``/mcp`` (the App Router page lives there
// too — it's the human-facing /mcp tab UI). Instead we condition the
// rewrite on the ``accept: text/event-stream`` header that MCP
// Streamable HTTP clients (Claude Desktop, Cursor, Cline) always send.
// Browsers fetching the dashboard page send ``accept: text/html`` and
// fall through to the App Router page.
const WORM_CORE_MCP_HOST =
  process.env.WORMBASE_WORM_CORE_HOST ?? "worm-core";
const WORM_CORE_MCP_PORT = process.env.WORMBASE_MCP_PORT ?? "9911";
const MCP_DESTINATION_BASE = `http://${WORM_CORE_MCP_HOST}:${WORM_CORE_MCP_PORT}`;

const nextConfig = {
  reactStrictMode: true,
  transpilePackages: ["@wormbase/design"],
  // pg is a CJS module that pulls in pg-native bindings — keep it
  // external from Next's bundler so the runtime resolves it from
  // node_modules at request time.
  serverExternalPackages: ["pg"],
  async rewrites() {
    return [
      // Server-side proxy: MCP Streamable HTTP traffic landing on the
      // dashboard origin (typically the cloudflared tunnel host) is
      // forwarded over the compose network to worm-core's FastMCP
      // server. The ``has: accept = text/event-stream`` matcher keeps
      // the human-facing /mcp App Router page reachable from browsers,
      // which always ask for text/html.
      {
        source: "/mcp",
        has: [
          {
            type: "header",
            key: "accept",
            value: ".*text/event-stream.*",
          },
        ],
        destination: `${MCP_DESTINATION_BASE}/mcp`,
      },
      // ``/mcp/<anything>`` is never the dashboard's own page (the App
      // Router only registers ``/mcp`` as a route). Forward unconditionally
      // so JSON-only POSTs and any sub-paths the MCP server might add
      // later all reach worm-core. ``/api/v1/mcp/...`` (the dashboard's
      // own MCP token API) is in a different segment and is unaffected.
      {
        source: "/mcp/:path*",
        destination: `${MCP_DESTINATION_BASE}/mcp/:path*`,
      },
    ];
  },
};

export default nextConfig;
